# Generated by Django 3.0.6 on 2020-05-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_code', models.CharField(max_length=50)),
                ('resident_name', models.CharField(max_length=50)),
                ('monthly_rent', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('rent', models.FloatField(default='6000')),
                ('rent_paid', models.FloatField(blank=True, null=True)),
                ('elec_bill', models.FloatField()),
                ('elec_bill_paid', models.FloatField(blank=True, null=True)),
                ('flat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rents.Flat')),
            ],
        ),
    ]
